ssr_krakow_homepage:
    path:     /
    defaults: { _controller: SSRBundle:Cities/Krakow:index }

ssr_krakow_download:
    path:     /download
    defaults: { _controller: SSRBundle:Cities/Krakow:download }
    
ssr_krakow_api:
    path:     /api/{stopID}
    defaults: { _controller: SSRBundle:Cities/Krakow:api, stopID: 0 }
    